austral/austral

src/alpha.sml, src/ast.sml, src/c-backend.sml, src/compiler.sml, src/dast.sig, src/dast.sml, src/hir-pass.sml, src/hir.sig, src/hir.sml, src/lir-pass.sml, src/lir.sig, src/lir.sml, src/mir-pass.sml, src/mir.sig, src/mir.sml, src/module.sml, src/mono-type.sig, src/mono-type.sml, src/mtast.sig, src/mtast.sml, src/oast.sml, src/set.sml, src/tast.sig, src/tast.sml, src/type.sig, src/type.sml, test/valid/defrecord.au
This PR implements the `record` special form.
Additionally, the definition of the `Record` case in `Type.ty` has changed to use a map of slot names to types.
=> Record constructors

lib/Cli.ml, lib/Error.ml, lib/Linearity.ml, lib/ParserInterface.ml, lib/Span.ml, lib/Span.mli
Fixes #36 and fixes #37.
Example error report:
```
Error:
Title: Parse Error
Location:
Filename: 'examples/fib/Fibonacci.aum'
From: line 13, column 4
To: line 13, column 7
Description:
Error during parse.
Code:
11 |     function Main(root: Root_Capability): Root_Capability is
12 |         Fibonacci(30);
13 |         return root
14 |     end;
15 | end module body.
```
=> Add error type, better printing of errors in the terminal

examples/box/Box.aum, examples/buffer/Buffer.aum, examples/ref-to-record/RTR.aum, lib/AbstractionPass.ml, lib/Ast.ml, lib/Ast.mli, lib/BuiltIn.ml, lib/CodeGen.ml, lib/Cpp.ml, lib/Cpp.mli, lib/CppPrelude.ml, lib/Cst.ml, lib/Cst.mli, lib/Lexer.mll, lib/Linearity.ml, lib/Parser.mly, lib/Pervasive.ml, lib/Tast.ml, lib/Tast.mli, lib/TypeParser.ml, lib/TypeSystem.ml, lib/TypingPass.ml
Fixes #58
Formerly there was a special case where a path of the form `x.y` where `x` is a reference and `y` is a `Pointer` would have a type `Pointer[T]` instead of `Reference[Pointer[T], R]`. This special case has been removed.
=> Simplify how paths interact with references

examples/box/Box.aui, examples/box/Box.aum, examples/generic-typeclass/GenericTypeclass.aum, examples/memory/Memory.aum, examples/pointer-to-record/PTR.aum, examples/ref-to-record/RTR.aum, lib/Compiler.ml
=>  Update examples to use `Allocate_Array` instead of `Allocate`

examples/box/Box.aum, examples/memory/Memory.aum, lib/Type.ml, lib/Type.mli, lib/TypingPass.ml
Fix #162 
There was a truly catastrophic error in `handle_return_type_polymorphism` in the typing pass.
=> Fix handling return type polymorphism

examples/box/Box.aum, examples/generic-typeclass/GenericTypeclass.aum, examples/memory/Memory.aum, examples/pointer-to-record/PTR.aum, standard/src/Box.aum, test-programs/suites/006-linearity/009-unbox-twice/Test.aum
According to https://github.com/austral/austral.github.io/pull/37 `allocate` should now take a count.
=> Fix allocate usage

lib/Cli.ml, lib/CliEngine.ml, lib/MonoTypeBindings.ml, lib/MonoTypeBindings.mli, lib/Monomorphize.ml, lib/TypeBindings.ml, lib/TypeMatch.ml, lib/TypeSystem.ml, lib/TypingPass.ml, standard/Makefile
The changes in #322 were wrong. The actual failure came up in the standard library. I merged before CI passed because CI is too slow and because it passed locally, but that was because the Makefile uses the globally installed `austral` binary instead of local, just-built one. I fixed the Makefile and the bugs.
Not entirely happy with how monomorphization works. I should clean it up in the future.
=> Fix the build

lib/CliEngine.ml
The `--no-entrypoint` flag was missing an `o`.
=> Fix typo in CLI

lib/Escape.ml, test/CRendererTest.ml, test/dune
Escaped quotes and triple quotes weren't handled by the `Escape` module, so they would make their way into the C output. This fix adds  `\"` to `Escape.escape_list`, and `"` to `Escape.unescape_char`.
I also started on a unit test for `CRenderer`. Right now it's woefully incomplete, it just tests this behavior specifically.
=> Fix unescaped quotes in C output

lib/AcmCode.ml, lib/AcmSerialization.ml, lib/CodeGen.ml, lib/CombiningPass.ml, lib/Env.ml, lib/EnvExtras.ml, lib/ExportInstantiation.ml, lib/ExtractionPass.ml, lib/LinearityCheck.ml, lib/Monomorphize.ml, lib/Mtast.ml, lib/TastUtil.ml, lib/TypeMatch.ml, lib/TypeParser.ml, lib/TypeStripping.ml, lib/TypingPass.ml
Replace uses for `err` for errors that are internal compiler errors. Some ICEs also contain additional diagnostics now.
This is my first time working in OCaml so best practices might not have been followed. Please let me know if there are any corrections I should make.
This fixes a part of #256.
=> Use `internal_err` for ICEs instead of `err`

editor/austral.vim/README.md, editor/austral.vim/ftdetect/austral.vim, editor/austral.vim/ftplugin/austral.vim, editor/austral.vim/syntax/austral.vim
I am not familiar with both the vim configuration and the austral language, so the function is not sufficient,
but I wrote it because I thought it would be better than not having it.
PS: The configuration file was created by referring to the ada configuration.
=> Add vim configuration for austral

lib/Lexer.mll, lib/Parser.mly, test-programs/suites/001-trivial/012-else-if/README.md, test-programs/suites/001-trivial/012-else-if/Test.aum, test-programs/suites/001-trivial/012-else-if/program-stdout.txt
Fix "else if" failing to parse (#364). The issue seemed to be the `ELSE` (no `IF`) option matching first, since the parser wouldn't look ahead. This fix adds a new `else[whitespace]if` token, so the parser won't need to look ahead.
=> Fix parse failure on "else if" (#364)

lib/TypingPass.ml, lib/builtin/Memory.aui, lib/builtin/Memory.aum, standard/src/Buffer.aum
Should return `Address[T]` rather than `Pointer[T]` since it can be null.
Fixes #350
=> Fix resizeArray return type

standard/src/Buffer.aui, standard/src/Buffer.aum, standard/test/Buffer.aum
This PR implements the following functions for buffers:
- `swapTransform`: swap elements in place by transforming them through a function
- `inPlaceMap`: special case of map where the function is `T->T` so we can reuse storage.
- `map`: the generic `map` function, consumes the old buffer and returns a new one
=> Extend the Buffer API

lib/BuiltIn.ml, lib/builtin/Pervasive.aui, lib/builtin/Pervasive.aum, test-programs/suites/012-numbers/bitwise-operations/README.md, test-programs/suites/012-numbers/bitwise-operations/Test.aum, test-programs/suites/012-numbers/bitwise-operations/program-stdout.txt
This is an attempt to add BitwiseOperations typeclass and implementation to the pervasives module.  I did not add shift left and shift right as these can be achieved by multiplying or dividing by powers of 2.
=> Add BitwiseOperations typeclass to pervasives module

lib/CRenderer.ml, lib/CRepr.ml, lib/CodeGen.ml, test-programs/suites/011-bugs/github-375/README.md, test-programs/suites/011-bugs/github-375/Test.aum
Because struct initializers for global variables are not portable C.
Fixes #375
=> Fix: generated C code doesn't compile when defining a constant with a record type

lib/LinearityCheck.ml, test-programs/suites/011-bugs/github-373/README.md, test-programs/suites/011-bugs/github-373/Test.aum
=> Fix: linearity checker confused by renaming in record destructuring

lib/Parser.mly, standard/src/Buffer.aum
Saves parentheses.
Fixes #389.
=> Make dereferencing an atomic expression

lib/CodeGen.ml, test-programs/suites/001-trivial/014-named-records/README.md, test-programs/suites/001-trivial/014-named-records/Test.aum, test-programs/suites/001-trivial/014-named-records/program-stdout.txt
The earlier fix for this problem did not work in all cases. Specifically, named structs in the same module that depend on each other could still be generated in the wrong order. The C compiler would complain that the struct embedded in a struct definition was not fully defined.
I have very limited OCaml skills, having briefly used the language for a few months in 2002, and my attempt at a fix is messy and gross. I'm 100% certain there are better ways to put it together and have thought of a few. However, this messy fix is working for me and has unblocked my work on implementing a hashtable in Austral.
I'm sharing it here in case you can look at it and quickly see the easy and smart way of implementing it :-)
The point of the change is that we calculate a score for each named struct which …
=> Fix code generation of named structs that depend on each other

editor/vscode-austral/syntaxes/austral.tmLanguage.json
I misunderstood the grammar and used "&" instead of the word "borrow" :facepalm:
=> austral-vscode: fix borrow statement keyword

lib/Lexer.mll, test-programs/suites/011-bugs/github-422/README.md, test-programs/suites/011-bugs/github-422/Test.aum
Fixes #422. The spec does require line comments to end with a newline character, but I think that's an unnecessary restriction, so I'm happy to update it too if this is okay.
=> Lex line comments with no trailing newline.

lib/LinearityCheck.ml, lib/TypeErrors.ml, lib/TypingPass.ml, test-programs/suites/006-linearity/013-no-assignment/Test.aum, test-programs/suites/006-linearity/013-no-assignment/austral-stderr.txt, test-programs/suites/006-linearity/014-assign-after-consume/README.md, test-programs/suites/006-linearity/014-assign-after-consume/Test.aum
=> Allow assigning to a linear variable once it's been consumed

lib/LinearityCheck.ml, lib/LinearityCheck.mli, test-programs/suites/006-linearity/007-outside-for-loop/README.md, test-programs/suites/006-linearity/007-outside-for-loop/austral-stderr.txt, test-programs/suites/006-linearity/015-consume-and-assign-in-loop/README.md, test-programs/suites/006-linearity/015-consume-and-assign-in-loop/Test.aum
=> Allow consuming linear variables in loops if you put them back

test-programs/runner.py
Tiny PR to let `test-programs/runner.py` filter tests by name.
New command line syntax is `test-programs/runner.py [SUITE] [TEST]` (both `SUITE` and `TEST` are optional).
Test suites that don't *contain* the string `SUITE` are skipped.
Of the suites run only tests containing the string `TEST` are run.
**Examples**:
```sh
$  python3 test-programs/runner.py 011 244
011-bugs
github-244                                   PASS
```
```sh
$ python3 test-programs/runner.py 001
001-trivial
001-null-program                             PASS
002-embed                                    PASS
003-sizeof                                   PASS
004-for-loop                                 PASS
005-hello-world                              PASS
006-printable                                PASS
007-root-cap …
```
=> CLI Parameters to Filter Test Programs Run

lib/AbstractionPass.ml, lib/Ast.ml, lib/CodeGen.ml, lib/Cst.ml, lib/Error.ml, lib/Lexer.mll, lib/LinearityCheck.ml, lib/Monomorphize.ml, lib/Mtast.ml, lib/Parser.mly, lib/Tast.ml, lib/TastUtil.ml, lib/TypeCheckExpr.ml, lib/TypeErrors.ml, lib/TypeReplace.ml, lib/TypingPass.ml, standard/src/Buffer.aum, test-programs/suites/007-borrowing/012-cant-reborrow-twice/README.md, test-programs/suites/007-borrowing/012-cant-reborrow-twice/Test.aum, test-programs/suites/007-borrowing/012-cant-reborrow-twice/austral-stderr.txt, test-programs/suites/007-borrowing/013-reborrow-expr/README.md, test-programs/suites/007-borrowing/013-reborrow-expr/Test.aum, test-programs/suites/007-borrowing/013-reborrow-expr/program-stdout.txt
This PR is built on top of #451 
This implements reborrowing expressions, which take a linear mutable reference, and, without consuming it, transform it into another linear mutable reference to a different region.
=> Reborrow expr

standard/src/Buffer.aum, standard/test/Buffer.aum
Fix #469 by adding a conditional guard to Buffer:initializeSafe for when 0 is passed to Buffer:initialize. A corresponding test is added in the Buffer module
=> Fix Standard.Buffer:initialize fails with size=0 

test-programs/suites/006-linearity/018-consume-and-assign-in-if/README.md, test-programs/suites/006-linearity/018-consume-and-assign-in-if/Test.aum
This is different to cases 003-005 because the variable is replaced after being consumed - which makes it legal to only reference the variable in a single branch.
Happy to add more combinations here if you want the test to be more comprehensive!
=> Test consuming and assigning a variable in one branch of an if-else

examples/box/Box.aum, examples/buffer/Buffer.aum, examples/ref-to-record/RTR.aum, lib/Lexer.mll, lib/Parser.mly, test-programs/suites/007-borrowing/001-explicit-read/Test.aum, test-programs/suites/007-borrowing/004-explicit-borrow-after-consume/Test.aum, test-programs/suites/007-borrowing/004-explicit-borrow-after-consume/austral-stderr.txt, test-programs/suites/007-borrowing/006-nested-explicit-borrow/Test.aum, test-programs/suites/007-borrowing/007-nested-explicit-anon-borrow/Test.aum, test-programs/suites/007-borrowing/009-dereference-linear/Test.aum, test-programs/suites/007-borrowing/009-dereference-linear/austral-stderr.txt, test-programs/suites/007-borrowing/010-dereference-free/Test.aum, test-programs/suites/007-borrowing/011-drop-mutable-ref/Test.aum, test-programs/suites/007-borrowing/012-cant-reborrow-twice/Test.aum, test-programs/suites/007-borrowing/012-cant-reborrow-twice/austral-stderr.txt, test-programs/suites/007-borrowing/013-reborrow-expr/Test.aum, test-programs/suites/007-borrowing/014-reborrow-stmt/Test.aum, test-programs/suites/007-borrowing/016-borrow-free/Test.aum, test-programs/suites/008-typeclasses/001-trivial-typeclass/Test.aum, test-programs/suites/011-bugs/github-413/Test.aum, test-programs/suites/013-ref-transforms/002-not-a-record/Test.aum, test-programs/suites/013-ref-transforms/002-not-a-record/austral-stderr.txt, test-programs/suites/013-ref-transforms/003-read-refs/Test.aum, test-programs/suites/015-mutability/003-cant-mutborrow-let/Test.aum, test-programs/suites/015-mutability/003-cant-mutborrow-let/austral-stderr.txt, test-programs/suites/016-spans/002-get-span/Test.aum
Before:
```austral
-- Immutable borrow
borrow foo as bar in R do
-- etc.
end;
-- Mutable borrow
borrow! foo as bar in R do
-- etc.
end;
-- Reborrow
borrow~ foo as bar in R do
-- etc.
end;
```
Now:
```austral
-- Immutable borrow
borrow foo: &[T, R] := &bar do
-- etc.
end borrow;
-- Mutable borrow
borrow foo: &![T, R] := &!bar do
-- etc.
end borrow;
-- Reborrow
borrow foo: &[T, R] := &~bar do
-- etc.
end borrow;
```
Pros:
1. Types are written down.
2. More consistent, less English-y.
3. `end borrow` rather than a bare `end`.
Cons:
1. More wordy.
See also: https://github.com/austral/austral/discussions/479
=> Better syntax for the borrow statement

.gitignore, Makefile, flake.lock, flake.nix
- Create flake.nix with
- default package - can be built and ran with `nix build` and `nix run`
- default devShell - enter with `nix develop`. I decided not to import the existing `shell.nix` since it's trivial, although I could if you prefer.
- add `PREFIX` to Makefile to support installing to different locations (eg nix store)
- add nix's `result` symlink to the `.gitignore`
=> Add flake.nix

editor/austral-mode.el
This fixes #568.
Before:
After:
=> austral-mode: indent function body too. Fix #568.

lib/TypeErrors.ml, lib/TypingPass.ml
The error message looks like this:
```
Description:
Cannot borrow the variable `root` mutably because it is a function parameter, and therefore immutable.
You can move it to a mutable local variable: `var mut_root: RootCapability := root;`
Code:
24 |     function main(root: RootCapability): ExitCode is
25 |         printLn("Hello, world!");
26 |         var term: TerminalCapability := acquireTerminal(&!root);
27 |         releaseTerminal(term);
28 |         return ExitSuccess();
```
=> Add suggested solution to error message.

lib/TypeErrors.ml, lib/TypingPass.ml
Original message:
```
Description:
The set of slots in the case statement doesn't match
the set of slots in the union definition:
Code:
7 |         let integer: Int32 := 1234;
8 |         printLn(integer);
9 |         case toFloat64(integer) of
10 |             when Some(float: Float64) do
11 |                 printLn(float);
12 |                 printLn(float/3);
13 |             when None do
14 |                 printLn("Failed to convert number.");
15 |         end case;
16 |         surrenderRoot(mut_root);
17 |         return ExitSuccess();
```
After this change:
```
Description:
The set of slots (`float`) in the case statement doesn't match
the set of slots in the union definition (`value`).
Code:
7 |         let integer: Int32 := 1234;
8 |         printLn(integer);
9 |         case …
```
=> Error messages: add details to error about enum slots mismatch.

editor/austral-mode.el
This fixes #572. It first computes the indentation based on the previous non-blank line, then adjusts it if the current line should be de-indented because it has `end` or closing parenthesis.
Before this fix, indenting the whole file:
After this fix:
=> austral-mode: correct indentation, fix #572.

editor/austral-mode.el
Can be tested on `examples/fib/Fibonacci.aum`.
=> austral-mode: correct indentation for `else`.

examples/greet/Greet.aui, examples/greet/Greet.aum, run-examples.sh
fixes #545
I have had to modify the run-examples.sh to use the stdlib and to provide some input to stdin.
This example doesn't actually work correctly yet because Standard.IO.Terminal.readLine doesn't work correctly, see #577.
=> add Example.Greet

lib/Util.ml
I do not see any reason for encoding `'\n'` as 97 when the other characters match their ASCII code so I assume this was a typo, but again I’m not familiar with OCaml and there might be some reason behind this.
If it was a typo, this fixes #577.
=> Correct integer encoding of '\n' newline char constant literal.

editor/vscode-austral/.gitignore, editor/vscode-austral/LICENSE, editor/vscode-austral/README.md, editor/vscode-austral/package-lock.json, editor/vscode-austral/package.json
Currently building the VS Code extension has a few minor annoyances:
- `vsce` is not in `devDependencies` so it must be installed globally
- there is no `repository` field so the user must manually type `y` and hit enter to bypass
- similarly there is no `LICENSE` file in that dir, again requiring `y` and hitting enter
- the generated `*.vsix` file is not gitignored
This PR resolves all those issues, making it smoother and easier to install the VS Code extension.
=> Clean up VS Code extension build process

standard/src/String.aum, standard/test/String.aum
As demonstrated by the added test case, currently `fromLiteral` aborts with the following error message when given an empty string:
```
Overflow in trappingSubtract (Index)
```
This PR fixes the bug by adding a check for zero size.
Incidentally, this really makes me think that it's unwise for the `for` loop to be inclusive on both ends, since it means that every `for` loop that doesn't want to crash on the zero case must special-case it. Since `Index` is unsigned, wouldn't it make more sense to provide a way to do an inclusive-exclusive range, like most languages do? E.g., Rust:
```rust
for i in 0..size {
// ...
}
```
=> Fix `fromLiteral` for empty string

.github/workflows/build-and-test.yml
Similar to #593, it'd be nice if the "Build and Test" workflow ran on PRs, so that contributors can tell whether a PR passes the tests before merging.
=> Run CI on PRs

examples/Makefile, examples/README.md, examples/ffi/Makefile, examples/fib/Makefile, examples/generic-record/Makefile, examples/generic-union/Makefile, examples/greet/Makefile, examples/haversine/Makefile, examples/hello-world/Makefile, examples/identity/Makefile, examples/memory/Makefile, examples/named-argument/Makefile, examples/record/Makefile, examples/union/Makefile
Building the examples presents a source of friction to new users who want to experiment with the language. This is especially true when an example needs to be compiled with the standard library. This commit adds a standard Makefile for examples to make them easy to build and provides a template for adding new examples.
=> Add Makefiles to examples

standard/src/IO/Terminal.aum
the writeByte implementation for StandardError and the readByte implementation for StandardInput now use the correct stream types rather than StandardOutput
=> Correct stream types in Standard.IO.Terminal

.github/workflows/build-and-test.yml
The `DeterminateSystems/magic-nix-cache-action` action has been [deprecated](https://determinate.systems/posts/magic-nix-cache-free-tier-eol/) and no longer works. This PR replaces it with the `nix-community/cache-nix-action` action, which is actively maintained. It also replaces the `DeterminateSystems/nix-installer-action` action with the `nixbuild/nix-quick-install-action` action, which is required for the cache action to work. The cache has been configured to restore based on the runner's OS and architecture, so it should work on any runner.
=> Replace magic-nix-cache-action

.github/workflows/build-and-test.yml
When I submitted my previous PR #613, I noticed the CI was failing because the `actions/upload-artifact` action was on v2, which is deprecated and no longer works, so this PR bumps it to v4 which is the latest version.
=> Upgrade actions/upload-artifact action to v4
