austral/austral

README.md, TODO.txt, src/parser.sml, src/syntax.sig, src/syntax.sml, test/test.sml
Lisp -> normie casual curly braces
=> Rewrite parser/syntax

lib/Util.ml, lib/Util.mli, lib/dune, test/UtilTest.ml, test/dune
=> Add a utility function to run a command and return its output

lib/Compiler.ml, lib/Compiler.mli, lib/Util.ml, lib/Util.mli, test/ExampleProgramTest.ml, test/dune
=> Add a utility to compile and run Austral programs from OCaml

lib/AbstractionPass.ml, lib/Cli.ml, lib/Compiler.ml, lib/Compiler.mli, lib/Cst.ml, lib/Cst.mli, lib/Parser.mly, lib/ParserInterface.ml, lib/ParserInterface.mli, lib/Span.ml, test/ExpressionParserTest.ml, test/TestUtil.ml, test/dune
=> Add position tracking

test/LinearityTest.ml, test/dune
=> Add unit tests of the linear type checker

lib/AbstractionPass.ml, lib/Pervasive.ml, lib/TypingPass.ml
=> Use trapping arithmetic

lib/TypingPass.ml, standard/src/Buffer.aui, standard/src/Buffer.aum
=> Insertion-related code

examples/box/Box.aum, examples/buffer/Buffer.aum, examples/ref-to-record/RTR.aum, lib/AbstractionPass.ml, lib/Ast.ml, lib/Ast.mli, lib/CodeGen.ml, lib/Cpp.ml, lib/Cpp.mli, lib/CppRenderer.ml, lib/Cst.ml, lib/Cst.mli, lib/Lexer.mll, lib/Linearity.ml, lib/Parser.mly, lib/Tast.ml, lib/Tast.mli, lib/TypingPass.ml, standard/src/Box.aum, standard/src/Buffer.aum
=> Dereferencing

lib/AbstractionPass.ml, lib/Ast.ml, lib/Ast.mli, lib/CodeGen.ml, lib/Cpp.ml, lib/Cpp.mli, lib/CppRenderer.ml, lib/Cst.ml, lib/Cst.mli, lib/Lexer.mll, lib/Linearity.ml, lib/Parser.mly, lib/Tast.ml, lib/Tast.mli, lib/TypingPass.ml, test/ExampleProgramTest.ml
=> Add sizeof operator

examples/array/Array.aum, examples/buffer/Buffer.aum, lib/BuiltIn.ml, lib/BuiltIn.mli, lib/CodeGen.ml, lib/CppPrelude.ml, lib/TypeParser.ml, lib/TypingPass.ml, standard/src/Buffer.aum
=> Merge Pointer and Heap_Array types

lib/BuiltIn.ml, lib/CppPrelude.ml
=> Add memmove and memcpy

examples/box/Box.aum, lib/BuiltIn.ml, lib/BuiltIn.mli, lib/CodeGen.ml, lib/Type.ml, lib/Type.mli, lib/TypeMatch.ml, lib/TypeParser.ml, lib/TypeParser.mli, lib/TypeSystem.ml, lib/TypeSystem.mli, lib/TypingPass.ml, test/TypeMatchTest.ml
=> First class raw pointer

lib/Mtast.ml, lib/Mtast.mli, lib/index.mld
=> Add types to represent a monomorphic AST

lib/Monomorphize.ml, lib/Monomorphize.mli
=> Replace tyvars in typed expressions and statements

lib/BuiltIn.ml, lib/CppPrelude.ml
=> Add pointer offset functions

lib/Compiler.ml, lib/ExtractionPass.ml, lib/ExtractionPass.mli, lib/Linked.ml, lib/Util.ml, lib/Util.mli, test/UtilTest.ml
=> Update extraction pass to return the linked representation

lib/CodeGen.ml, lib/Compiler.ml, lib/Env.ml, lib/Env.mli, lib/ExtractionPass.ml, lib/ExtractionPass.mli, lib/Id.ml, lib/Id.mli, lib/ImportResolution.ml, lib/Imports.ml, lib/Imports.mli, lib/Linked.ml, lib/Tast.ml, lib/Tast.mli, lib/TypingPass.ml, lib/TypingPass.mli
=> Update typing pass to use the linked representation

lib/BodyExtractionPass.ml, lib/BodyExtractionPass.mli, lib/CodeGen.ml, lib/Linearity.ml, lib/Tast.ml, lib/Tast.mli, lib/TypingPass.ml, lib/Util.ml, lib/Util.mli
=> Add an extraction pass to store typed function/method bodies in the environment

lib/CodeGen.ml, lib/Env.ml, lib/Env.mli, lib/Linearity.ml, lib/Monomorphize.ml, lib/Tast.ml, lib/Tast.mli, lib/TypingPass.ml
=> Store declaration IDs in typed AST

lib/Env.ml, lib/Env.mli
=> Support storing monomorphs in the environment

lib/CRepr.ml, lib/CodeGen2.ml, lib/CodeGen2.mli
=> Implement codegen from MTAST to the C AST

examples/buffer/Buffer.aum, examples/generic-typeclass/GenericTypeclass.aum, lib/AbstractionPass.ml, lib/Ast.ml, lib/Common.ml, lib/Common.mli, lib/Compiler.ml, lib/Escape.ml, lib/Escape.mli, lib/Id.ml, lib/Id.mli, lib/ReturnCheck.ml, lib/ReturnCheck.mli, lib/Span.ml, lib/Span.mli, lib/Tast.ml, lib/Tast.mli, lib/TypingPass.ml
=> Add a check to ensure every function ends in a return or abort

examples/concrete-typeclass/ConcreteTypeclass.aum, examples/generic-typeclass/GenericTypeclass.aum, lib/Lexer.mll, lib/Pervasive.ml
=> Rename interface/implementation to typeclass/instance

lib/Cli.ml, lib/Reporter.ml, lib/Reporter.mli
=> Add a compiler reporting framework

examples/buffer/Buffer.aui, examples/buffer/Buffer.aum, examples/string/String.aum, lib/CPrelude.ml, lib/CodeGen.ml, lib/Compiler.ml, lib/Tast.ml, lib/Type.ml, lib/Type.mli, lib/TypeParser.ml, lib/TypingPass.ml, lib/builtin/Memory.aui, lib/builtin/Memory.aum, lib/builtin/Pervasive.aui, lib/builtin/Pervasive.aum, lib/prelude.c, test/ExampleProgramTest.ml
=> Add Index type

lib/CodeGen.ml, lib/MonoType.ml, lib/Monomorphize.ml, lib/Type.ml, lib/Type.mli, lib/TypeBindings.ml, lib/TypeMatch.ml, lib/TypeParser.ml, lib/TypeStripping.ml, lib/TypeStripping.mli, lib/TypeSystem.ml, lib/TypingPass.ml
=> Rename Array to Static_Array and drop the region argument

lib/Combined.ml, lib/CombiningPass.ml, lib/Compiler.ml, lib/Env.ml, lib/Env.mli, lib/ExtractionPass.ml, lib/ExtractionPass.mli, lib/Linked.ml, lib/Monomorphize.ml, lib/Tast.ml, lib/Tast.mli, lib/Type.ml, lib/Type.mli, lib/TypeMatch.ml, lib/TypeMatch.mli, lib/TypeParameters.ml, lib/TypeParameters.mli, lib/TypeParser.ml, lib/TypeParser.mli, lib/TypeSignature.ml, lib/TypeSystem.ml, lib/TypeSystem.mli, lib/TypingPass.ml, lib/index.mld
=> Store type parameters in a set

lib/Lexer.mll, lib/Span.ml
=> Track source positions correctly

examples/box/Box.aui, examples/box/Box.aum, lib/Ast.ml, lib/Cst.ml, lib/Cst.mli, lib/Lexer.mll, lib/Parser.mly, lib/Qualifier.ml, lib/TypeParser.ml
=> Syntactic sugar for reference types

lib/DeclIdSet.ml, lib/Env.ml, lib/Env.mli, lib/ExtractionPass.ml
=> Store instances

lib/ExtractionPass.ml, lib/TypeClasses.ml, lib/TypeClasses.mli, test-programs/suites/009-typeclasses/007-trivial-duplicate/README.md, test-programs/suites/009-typeclasses/007-trivial-duplicate/Test.aui, test-programs/suites/009-typeclasses/007-trivial-duplicate/Test.aum, test-programs/suites/009-typeclasses/007-trivial-duplicate/error.txt, test-programs/suites/009-typeclasses/008-named-duplicate/README.md, test-programs/suites/009-typeclasses/008-named-duplicate/Test.aui, test-programs/suites/009-typeclasses/008-named-duplicate/Test.aum, test-programs/suites/009-typeclasses/008-named-duplicate/error.txt, test-programs/suites/009-typeclasses/009-generic-duplicate/README.md, test-programs/suites/009-typeclasses/009-generic-duplicate/Test.aui, test-programs/suites/009-typeclasses/009-generic-duplicate/Test.aum, test-programs/suites/009-typeclasses/009-generic-duplicate/error.txt
=> Implement local instance uniqueness

lib/Env.ml, lib/Env.mli, lib/ExtractionPass.ml, lib/Imports.ml, lib/Imports.mli, lib/ModIdSet.ml, lib/ModuleNameSet.ml
=> Store imported modules

lib/Cli.ml, lib/Compiler.ml, lib/Error.ml, lib/Error.mli, lib/ErrorText.ml, lib/ErrorText.mli, lib/ParserInterface.ml, lib/TypeMatch.ml, test/ExampleProgramTest.ml
=> Structured representation of errors

lib/TypeMatch.ml, test-programs/suites/009-typeclasses/011-unconstrained-typaram/README.md, test-programs/suites/009-typeclasses/011-unconstrained-typaram/Test.aui, test-programs/suites/009-typeclasses/011-unconstrained-typaram/Test.aum, test-programs/suites/009-typeclasses/011-unconstrained-typaram/error.txt, test/TypeMatchTest.ml
=> Add a unit test of unconstrained type parameters

lib/CombiningPass.ml, lib/Cst.ml, lib/Cst.mli, lib/ExtractionPass.ml, lib/Monomorphize.ml, lib/Parser.mly, lib/Type.ml, lib/Type.mli, lib/TypeMatch.ml, lib/TypeParameters.ml, lib/TypeParser.ml, lib/TypingPass.ml
=> Parsing type parameter constraints

lib/Env.ml, lib/Env.mli, lib/EnvExtras.ml, lib/EnvExtras.mli, lib/TypeClasses.ml, lib/TypeClasses.mli, lib/TypingPass.ml, lib/TypingPass.mli
=> Implement instance resolution correctly

.github/workflows/build-and-test.yml, README.md, install-ocaml-deps.sh
=> Add a script to install OCaml dependencies

lib/ExtractionPass.ml, test-programs/suites/003-record/002-free-record-has-linear/README.md, test-programs/suites/003-record/002-free-record-has-linear/Test.aum, test-programs/suites/003-record/002-free-record-has-linear/error.txt, test-programs/suites/004-union/002-free-union-has-linear/README.md, test-programs/suites/004-union/002-free-union-has-linear/Test.aum, test-programs/suites/004-union/002-free-union-has-linear/error.txt
=> Add a test of defining a Free type that contains a Linear type

concat_builtins.py, lib/BuiltInModules.mli, lib/Compiler.ml, lib/prelude.h
=> Store the prelude interface in a .h file

lib/CodeGen.ml, lib/MonoType.ml, lib/Monomorphize.ml, lib/Type.ml, lib/Type.mli, lib/TypeBindings.ml, lib/TypeClasses.ml, lib/TypeMatch.ml, lib/TypeStripping.ml, lib/TypeStripping.mli, lib/TypeSystem.ml, lib/prelude.c, lib/prelude.h
=> Add function pointer type to the type system

Makefile, README.md, lib/CRenderer.ml, lib/CRepr.ml, lib/CodeGen.ml, lib/Compiler.ml, lib/Util.ml, lib/prelude.c, run-examples.sh, test-programs/runner.py
=> Include prelude source code in generated code

lib/prelude.c
=> Fix stderr failures

lib/prelude.c
=> Fix stderr issue on OpenBSD

lib/Compiler.ml, lib/Entrypoint.ml, lib/Entrypoint.mli, lib/index.mld
=> Move entrypoint logic to its own module

lib/Error.ml
Ref #256 
Ask users to report internal compiler errors as issues
=> Include link to GitHub issues when printing an internal error

lib/Entrypoint.ml, lib/Error.ml, lib/Error.mli
Ref #256 
Report a bit more info
=> Improve the diagnostics for checks of the entrypoint functions

lib/BuiltIn.ml, lib/Entrypoint.ml, lib/builtin/Pervasive.aui, lib/builtin/Pervasive.aum, lib/prelude.c, lib/prelude.h, test-programs/suites/001-trivial/010-cli/README.md, test-programs/suites/001-trivial/010-cli/Test.aum, test-programs/suites/001-trivial/010-cli/program-stdout.txt
=> Support command line arguments in the entrypoint function

lib/Env.ml, lib/Env.mli, lib/ImportResolution.ml, test-programs/suites/008-typeclasses/016-private-instance/Foreign.aui, test-programs/suites/008-typeclasses/016-private-instance/Foreign.aum, test-programs/suites/008-typeclasses/016-private-instance/README.md, test-programs/suites/008-typeclasses/016-private-instance/Test.aum, test-programs/suites/008-typeclasses/016-private-instance/austral-stderr.txt, test-programs/suites/008-typeclasses/016-private-instance/cli.txt
=> Fix private instances being imported

lib/CliUtil.ml, lib/CliUtil.mli
=> Add CLI parsing utility

lib/CliParser.ml, lib/CliParser.mli, lib/CliUtil.ml, lib/CliUtil.mli
=> Add a CLI parsing module

README.md, bin/austral.ml, lib/Cli.ml, lib/CliEngine.ml, lib/CliEngine.mli, lib/CliParser.ml, lib/CliParser.mli, lib/CliUtil.ml, lib/CliUtil.mli, lib/Compiler.ml, lib/Compiler.mli, lib/Util.ml, lib/Version.ml, run-examples.sh, test-programs/runner.py, test-programs/suites/001-trivial/009-docstrings/cli.txt, test-programs/suites/008-typeclasses/013-orphan-instance/cli.txt, test-programs/suites/008-typeclasses/014-local-tc-foreign-type/cli.txt, test-programs/suites/008-typeclasses/015-foreign-tc-local-type/cli.txt, test-programs/suites/008-typeclasses/016-private-instance/cli.txt, test/CliParserTest.ml, test/CliUtilTest.ml, test/dune
=> New command line interface

lib/AcmFile.ml, lib/Combined.ml, lib/CombiningPass.ml, lib/EnvTypes.ml, lib/ExtractionPass.ml, lib/Linked.ml, lib/Monomorphize.ml, lib/Tast.ml, lib/Type.ml, lib/Type.mli, lib/TypeMatch.ml, lib/TypeParameter.ml, lib/TypeParameter.mli, lib/TypeParameters.ml, lib/TypeParameters.mli, lib/TypeParser.ml, lib/TypingPass.ml, lib/index.mld
Progress towards #313
Ref #313
=> Make type_parameter an opaque type

standard/Makefile, standard/src/Buffer.aui, standard/src/Buffer.aum, standard/test/Buffer.aui, standard/test/Buffer.aum, standard/test/Main.aum, standard/test/Unit.aui, standard/test/Unit.aum
=> Add simple Buffer type to stdlib

standard/Makefile, standard/src/Equality.aui, standard/src/Equality.aum, standard/test/Equality.aui, standard/test/Equality.aum, standard/test/Main.aum
=> Typeclasses for partial and total equivalence relations

lib/CodeGen.ml, standard/Makefile, standard/src/Order.aui, standard/src/Order.aum, standard/test/Main.aum, standard/test/Order.aui, standard/test/Order.aum
=> Typeclasses for partial and total ordering relations

lib/AcmFile.ml, lib/CodeGen.ml, lib/Entrypoint.ml, lib/Env.ml, lib/Env.mli, lib/EnvTypes.ml, lib/MonoTypeBindings.ml, lib/MonoTypeBindings.mli, lib/Monomorphize.ml, lib/Tast.ml, lib/TypeBindings.ml, lib/TypeBindings.mli, lib/TypeReplace.ml, lib/TypingPass.ml, lib/TypingPass.mli, lib/index.mld
=> Use a map to store monomorph type substitutions

lib/AcmCode.ml, lib/AcmFile.ml, lib/CodeGen.ml, lib/LinearityCheck.ml, lib/Monomorphize.ml, lib/Mtast.ml, lib/Tast.ml, lib/TastUtil.ml, lib/TypeReplace.ml, lib/TypingPass.ml, test-programs/suites/010-functions/002-concrete-f-as-value/README.md, test-programs/suites/010-functions/002-concrete-f-as-value/Test.aum, test-programs/suites/010-functions/003-generic-f-as-value/README.md, test-programs/suites/010-functions/003-generic-f-as-value/Test.aum
=> Accessing functions as values

examples/array/Array.aum, examples/box/Box.aum, examples/buffer/Buffer.aum, examples/generic-typeclass/GenericTypeclass.aum, examples/memory/Memory.aum, examples/pointer-to-record/PTR.aum, lib/TastUtil.ml, lib/builtin/Memory.aui, lib/builtin/Memory.aum, standard/src/Box.aum, standard/src/Buffer.aum, test-programs/suites/006-linearity/009-unbox-twice/Test.aum
=> Improve allocate API

lib/CliEngine.ml, lib/CodeGen.ml, lib/CodeGen.mli, lib/Common.ml, lib/Compiler.ml, lib/Compiler.mli, lib/CstUtil.ml, lib/Env.ml, lib/Env.mli, lib/ExportInstantiation.ml, lib/ExportInstantiation.mli, lib/ExtractionPass.ml, lib/Monomorphize.ml, lib/Monomorphize.mli, lib/TypingPass.ml, lib/index.mld, test-programs/suites/010-functions/004-export-function/README.md, test-programs/suites/010-functions/004-export-function/Test.aum
=>  C FFI: export an Austral function

lib/builtin/Pervasive.aum, lib/prelude.c
=> Revert "Use generics in trapping arithmetic"

standard/src/Buffer.aui, standard/src/Buffer.aum, standard/test/Buffer.aum
Right now `Buffer` in the standard library is very spartan.
=> Improve the Buffer API

lib/AcmCode.ml, lib/AcmFile.ml, lib/CodeGen.ml, lib/LinearityCheck.ml, lib/Monomorphize.ml, lib/Mtast.ml, lib/Tast.ml, lib/TastUtil.ml, lib/TypeReplace.ml, lib/TypingPass.ml
=> Remove unused arithmetic nodes

lib/TypeParser.ml
When a type has $n$ type parameters, but a type specifier for that type has $m \neq n$ type parameters, we raise a nicer error message. Previously we just threw an assert.
See: #359
=> Better error reporting for generic type arity mismatch

editor/austral.vim/ftplugin/austral.vim, editor/austral.vim/syntax/austral.vim
Thanks for accepting the pull request! There was a problem with the previous configuration, so I improved it a little.
* Fix unmatched syntax
* Add missing keywords
* Improve syntax highlighting
* Improve code readability
=> Update vim configuration files

test-programs/suites/010-functions/006-wrong-arity/README.md, test-programs/suites/010-functions/006-wrong-arity/Test.aum, test-programs/suites/010-functions/006-wrong-arity/austral-stderr.txt
=> Add a test of wrong arity errors

lib/CRenderer.ml, lib/CodeGen.ml, test-programs/suites/011-bugs/github-371/README.md, test-programs/suites/011-bugs/github-371/Test.aum
=> Fix: mutually-recursive types don't codegen

examples/generic-typeclass/GenericTypeclass.aum, lib/ExtractionPass.ml, lib/TypeClasses.ml, lib/TypeClasses.mli, test-programs/suites/008-typeclasses/001-trivial-typeclass/Test.aum, test-programs/suites/008-typeclasses/009-generic-duplicate/Test.aum, test-programs/suites/008-typeclasses/019-instance-method-typaram-overlap/Test.aum, test-programs/suites/011-bugs/github-244/README.md, test-programs/suites/011-bugs/github-244/Test.aum, test-programs/suites/011-bugs/github-244/austral-stderr.txt
=> Add a test of generic instance type parameter collisions

lib/CliParser.ml, lib/Error.ml, lib/Error.mli
=> Minor improvement of a CLI error message

standard/LICENSE, standard/README.md
=> Make the standard library Apache 2.0

lib/prelude.c, lib/prelude.h
=> Use fixed-size integer types in the prelude

lib/TypeMatch.ml, test-programs/suites/011-bugs/github-428/README.md, test-programs/suites/011-bugs/github-428/Test.aum
=> Add support for Float32 flexible type matching

lib/TypeMatch.ml, test-programs/suites/008-typeclasses/020-unsatisfied-constraint/README.md, test-programs/suites/008-typeclasses/020-unsatisfied-constraint/Test.aum, test-programs/suites/008-typeclasses/020-unsatisfied-constraint/austral-stderr.txt
=> Better error for unsatisfied type constraints

lib/ExtractionPass.ml, test-programs/suites/011-bugs/github-424/README.md, test-programs/suites/011-bugs/github-424/Test.aum, test-programs/suites/011-bugs/github-424/austral-stderr.txt
=> Fix: spurious generic crashes GCC

lib/LexEnv.ml, lib/LexEnv.mli, lib/TypeErrors.ml, lib/TypingPass.ml, test-programs/suites/010-functions/007-assign-param/README.md, test-programs/suites/010-functions/007-assign-param/Test.aum, test-programs/suites/010-functions/007-assign-param/austral-stderr.txt
=> Fix: assigning to function parameters should not work

lib/Reporter.ml
Switched tree view to html + cs rather than js.
Added buttons to open all and close all limbs of the tree.
=> Improved calltree 

docs/paths.md
=> Add path documentation

lib/LinearityCheck.ml, test-programs/suites/006-linearity/016-consume-and-assign/README.md, test-programs/suites/006-linearity/016-consume-and-assign/Test.aum
=> Allow assigning to a variable that's consumed on the right of the assignment

lib/ExtractionPass.ml, lib/Region.ml, lib/Region.mli, lib/RegionMap.ml, lib/RegionMap.mli, lib/TypeCheckExpr.ml, lib/TypeCheckExpr.mli, lib/TypeParser.ml, lib/TypeParser.mli, lib/TypingPass.ml
Preliminary work to resolve a cyclic dependency issue to then attack #468
=> Split Region into Region and RegionMap

lib/Type.ml, lib/Type.mli, test-programs/suites/007-borrowing/009-dereference-linear/austral-stderr.txt, test-programs/suites/008-typeclasses/004-expect-free/austral-stderr.txt, test-programs/suites/011-bugs/github-381/austral-stderr.txt, test-programs/suites/011-bugs/github-381b/austral-stderr.txt, test-programs/suites/013-ref-transforms/002-not-a-record/austral-stderr.txt
=> Simpler type printing

install-ocaml-deps.sh, lib/TypeMatch.ml, lib/dune, test-programs/suites/014-int-constants/001-nat8-neg/README.md, test-programs/suites/014-int-constants/001-nat8-neg/Test.aum, test-programs/suites/014-int-constants/001-nat8-neg/austral-stderr.txt, test-programs/suites/014-int-constants/002-nat16-neg/README.md, test-programs/suites/014-int-constants/002-nat16-neg/Test.aum, test-programs/suites/014-int-constants/002-nat16-neg/austral-stderr.txt, test-programs/suites/014-int-constants/003-nat32-neg/README.md, test-programs/suites/014-int-constants/003-nat32-neg/Test.aum, test-programs/suites/014-int-constants/003-nat32-neg/austral-stderr.txt, test-programs/suites/014-int-constants/004-nat64-neg/README.md, test-programs/suites/014-int-constants/004-nat64-neg/Test.aum, test-programs/suites/014-int-constants/004-nat64-neg/austral-stderr.txt, test-programs/suites/014-int-constants/005-nat8-overflow/README.md, test-programs/suites/014-int-constants/005-nat8-overflow/Test.aum, test-programs/suites/014-int-constants/005-nat8-overflow/austral-stderr.txt, test-programs/suites/014-int-constants/006-nat16-overflow/README.md, test-programs/suites/014-int-constants/006-nat16-overflow/Test.aum, test-programs/suites/014-int-constants/006-nat16-overflow/austral-stderr.txt, test-programs/suites/014-int-constants/007-nat32-overflow/README.md, test-programs/suites/014-int-constants/007-nat32-overflow/Test.aum, test-programs/suites/014-int-constants/007-nat32-overflow/austral-stderr.txt, test-programs/suites/014-int-constants/008-nat64-overflow/README.md, test-programs/suites/014-int-constants/008-nat64-overflow/Test.aum, test-programs/suites/014-int-constants/008-nat64-overflow/austral-stderr.txt
=> Ensure that integer constants fit in the types they're assigned to

lib/prelude.c, lib/prelude.h, standard/Makefile, standard/src/IO/IO.aui, standard/src/IO/IO.aum, standard/src/IO/Terminal.aui, standard/src/IO/Terminal.aum, standard/test/IO/Terminal.aui, standard/test/IO/Terminal.aum, standard/test/Main.aum
Adds capabilities and code for terminal I/O.
=> Standard library: terminal I/O

lib/builtin/Pervasive.aui, lib/builtin/Pervasive.aum
=> Add a Remainder typeclass

lib/CombiningPass.ml, lib/CstUtil.ml, lib/CstUtil.mli
=> Improve instance mismatch error

lib/CombiningPass.ml, lib/Cst.ml, lib/CstUtil.ml, lib/Parser.mly
=> Adorn errors in the combining pass

lib/Combined.ml, lib/CombiningPass.ml, lib/ExtractionPass.ml, lib/ReturnCheck.ml, test-programs/suites/003-record/002-free-record-has-linear/austral-stderr.txt, test-programs/suites/003-record/003-free-record-linear-param/austral-stderr.txt, test-programs/suites/003-record/004-record-in-region/austral-stderr.txt, test-programs/suites/004-union/002-free-union-has-linear/austral-stderr.txt, test-programs/suites/004-union/003-free-union-linear-param/austral-stderr.txt, test-programs/suites/004-union/004-union-in-region/austral-stderr.txt, test-programs/suites/008-typeclasses/002-region-param/austral-stderr.txt, test-programs/suites/008-typeclasses/003-expect-linear/austral-stderr.txt, test-programs/suites/008-typeclasses/004-expect-free/austral-stderr.txt, test-programs/suites/008-typeclasses/005-duplicate-tyvar/austral-stderr.txt, test-programs/suites/008-typeclasses/006-unused-tyvar/austral-stderr.txt, test-programs/suites/008-typeclasses/007-trivial-duplicate/austral-stderr.txt, test-programs/suites/008-typeclasses/008-named-duplicate/austral-stderr.txt, test-programs/suites/008-typeclasses/009-generic-duplicate/austral-stderr.txt, test-programs/suites/008-typeclasses/013-orphan-instance/austral-stderr.txt, test-programs/suites/008-typeclasses/018-typeclass-method-typaram-overlap/austral-stderr.txt, test-programs/suites/008-typeclasses/019-instance-method-typaram-overlap/austral-stderr.txt, test-programs/suites/009-names/001-dup-const-const/austral-stderr.txt, test-programs/suites/009-names/002-dup-rec-rec/austral-stderr.txt, test-programs/suites/009-names/003-dup-union-union/austral-stderr.txt, test-programs/suites/009-names/004-dup-fun-fun/austral-stderr.txt, test-programs/suites/011-bugs/github-244/austral-stderr.txt, test-programs/suites/011-bugs/github-359/austral-stderr.txt, test-programs/suites/011-bugs/github-424/austral-stderr.txt
=> Adorn errors with span in the extraction pass

lib/TypeErrors.ml, lib/TypingPass.ml, test-programs/suites/009-names/005-var-collides-decl/README.md, test-programs/suites/009-names/005-var-collides-decl/Test.aum, test-programs/suites/009-names/005-var-collides-decl/austral-stderr.txt, test-programs/suites/009-names/006-param-collides-decl/README.md, test-programs/suites/009-names/006-param-collides-decl/Test.aum, test-programs/suites/009-names/006-param-collides-decl/austral-stderr.txt
=> Test local variable names do not collide with declaration names

lib/CodeGen.ml, lib/Common.ml, lib/Cst.ml, lib/ExtractionPass.ml, lib/Lexer.mll, lib/LinearityCheck.ml, lib/Mtast.ml, lib/Parser.mly, lib/Stages.ml, lib/Tast.ml, lib/TypingPass.ml, test-programs/suites/007-borrowing/014-reborrow-stmt/README.md, test-programs/suites/007-borrowing/014-reborrow-stmt/Test.aum, test-programs/suites/007-borrowing/014-reborrow-stmt/program-stdout.txt
=> Add a reborrow statement

lib/Version.ml, test-programs/suites/006-linearity/017-cant-consume-in-while/README.md, test-programs/suites/006-linearity/017-cant-consume-in-while/Test.aum, test-programs/suites/006-linearity/017-cant-consume-in-while/austral-stderr.txt
=> Fix: we can't consume a linear variable in the condition of a while loop

lib/CodeGen.ml, lib/DesugarBorrows.ml, lib/LexEnv.ml, lib/LexEnv.mli, lib/LiftControlPass.ml, lib/LinearityCheck.ml, lib/Monomorphize.ml, lib/Stages.ml, lib/TypeReplace.ml, lib/TypingPass.ml
=> Stateful lexenv

lib/LinearityCheck.ml, test-programs/suites/006-linearity/018-consume-and-assign-in-if/README.md, test-programs/suites/006-linearity/018-consume-and-assign-in-if/Test.aum
=> Allow consume/replace in if branches

lib/CodeGen.ml, lib/ExportInstantiation.ml, lib/MonoType.ml, lib/Monomorphize.ml, lib/Type.ml, lib/Type.mli, lib/TypeBindings.ml, lib/TypeClasses.ml, lib/TypeMatch.ml, lib/TypeParser.ml, lib/TypeStripping.ml, lib/TypeStripping.mli, lib/TypeSystem.ml, lib/prelude.c, lib/prelude.h
=> Add array slice types

lib/Cst.ml, lib/CstUtil.ml, lib/Lexer.mll, lib/Parser.mly, lib/Qualifier.ml, lib/Stages.ml, lib/TypeParser.ml, test-programs/suites/016-spans/001-parser/README.md, test-programs/suites/016-spans/001-parser/Test.aum
=> Parse slice types

test-programs/suites/006-linearity/019-consume-and-assign-in-case/README.md, test-programs/suites/006-linearity/019-consume-and-assign-in-case/Test.aum
=> Add another test for consume/assign in case statements

test-programs/runner.py, test-programs/shell.nix, test-programs/suites/001-trivial/009-docstrings/cli.txt, test-programs/suites/001-trivial/010-cli/program-stdout.txt, test-programs/suites/008-typeclasses/013-orphan-instance/cli.txt, test-programs/suites/008-typeclasses/014-local-tc-foreign-type/cli.txt, test-programs/suites/008-typeclasses/015-foreign-tc-local-type/cli.txt, test-programs/suites/008-typeclasses/016-private-instance/cli.txt
Before: 35s locally, 60s on builds
After: 4s
=> Run end-to-end tests in parallel

lib/builtin/Memory.aui, lib/builtin/Memory.aum
=> Add functions to turn a span into a pointer

standard/src/Buffer.aui, standard/src/Buffer.aum, standard/test/Buffer.aum
=> stdlib: add functions to get spans from a Buffer

standard/src/String.aui, standard/src/String.aum
=> stdlib: add functions to get spans from a String

standard/src/String.aui, standard/src/String.aum
=> stdlib: fromByteBuffer for String

standard/Makefile, standard/src/StringBuilder.aui, standard/src/StringBuilder.aum, standard/test/Main.aum, standard/test/StringBuilder.aui, standard/test/StringBuilder.aum
=> stdlib: StringBuilder

standard/src/IO/Terminal.aui, standard/src/IO/Terminal.aum
=> stdlib: add a function to read a line as a String from stdin

.github/workflows/build-and-test.yml, README.md, lib/Error.mli
Described in: https://determinate.systems/posts/magic-nix-cache
=> Try the Magic Nix Cache

test-programs/runner.py
- avoids manually managing processes
- avoids need to sleep until they're done
- avoids need to pass in queue to `run_test`
- avoids process spam; `ProcessPoolExecutor` limits size of pool to number of CPU cores
- all processes are guaranteed to have exited after we successfully leave the `with` block
=> in test runner, use ProcessPoolExecutor instead of manually managing processes

lib/prelude.c
=> Fix macOS symbols

lib/CliEngine.ml
=> fix compiler helptext typo

.github/workflows/build-macos.yml
Resolves #589 by just following the tutorial: https://austral-lang.org/tutorial/getting-started-linux I also added the `pull_request` trigger to this workflow, because otherwise it's hard to tell whether a PR passes CI.
=> Follow tutorial instructions for macOS build
